---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(httr)
library(jsonlite)
```

```{r, include=FALSE}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows()
```
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Distribution of chinese cuisines in NYC

```{r}
nyc_inspections |>
  filter(grade %in% c('A','B','C'),
         cuisine_description == 'Chinese')|>
  drop_na(score)|>
  mutate(text_label = str_c("Score: ", score, "\nGrade: ", grade),
         latitude = as.character(round(as.numeric(latitude), 2)),
         longitude = as.character(round(as.numeric(longitude), 2))) |> 
  plot_ly(
    x = ~latitude, y = ~longitude, type = "scatter", mode = "markers",
    color = ~boro, alpha = 0.5, text = ~text_label) #text = ~text_label, alpha = 0.5
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Scores of Chinese restaurant across boroughs

```{r}
nyc_inspections |> 
  filter(cuisine_description == 'Chinese')|>
  plot_ly(y = ~as.numeric(score), x = ~boro, color = ~boro, type = "box", colors = "viridis")
```

### Chart C: Number of Chinese restaurant across boroughs

```{r}
nyc_inspections |> 
  filter(cuisine_description == 'Chinese')|>
  count(boro) |> 
  mutate(boro = fct_reorder(boro, n)) |> 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis")
```